#pragma once


enum ErrorCode
{
	ERROR_UNKNOWN = -1,

	ERROR_CREATE_DECODER = -100,
	ERROR_DECODE = -101,
	ERROR_FLUSH_DECODER = -102,

	ERROR_CREATE_ENCODER = -200,
	ERROR_ENCODE = -201,
	ERROR_FLUSH_ENCODER = -202,

	ERROR_CREATE_PUSHER = -300,
	ERROR_STOP_PUSHER = -301,
	ERROR_PUSH_PACKET = -302,

	ERROR_STARTPACK = -400,
	ERROR_ENDPACK = -401,
	ERROR_ADD_PACKET = -401,
	ERROR_OPEN_PACKAGE = -402,
	ERROR_CLOSE_PACKAGE = -403,

	ERROR_PACKET_REFERENCED = -500,

	ERROR_NO_CODEC = -1,
	ERROR_OPEN_CODEC = -2,
	ERROR_NO_OUTFMORTCONTEXT = -3,
	ERROR_CREATE_CODECCONTEXT = -4,
	ERROR_CREATE_OUTSTREAM = -5,
	ERROR_COPY_CODEC_PARAM = -6,
	ERROR_OPEN_URL = -7,
	ERROR_WRITEHEADER = -8,
	ERROR_WRITE_FRAME = -9,
	ERROR_WRITETRAILER = -10,
	ERROR_CLOSE_URL = -11,
	ERROR_OPEN_FORMATCONTEXT = -12,
	ERROR_NO_STREAM = -13,
	ERROR_PACKAGE_MODE = -14,
	ERROR_NO_BSF = -16,
	ERROR_ALLOC_BSF = -17,
	ERROR_INIT_BSF = -18,

};